application: thewallstall
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /admin/.*
  script: admin.py
  login: admin

- url: /admin
  script: redirector.py

- url: .*
  script: main.py
